# Generated by Django 4.2.4 on 2023-10-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteBin', '0003_alter_paste_expiration_date_delete_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
